namespace Iot.Device.Media.Interop;

internal enum VideoSettings
{
	// ReSharper disable InconsistentNaming
	VIDIOC_QUERYCAP,
	VIDIOC_ENUM_FMT,
	VIDIOC_CROPCAP,
	VIDIOC_G_CROP,
	VIDIOC_S_CROP,
	VIDIOC_G_FMT,
	VIDIOC_S_FMT,
	VIDIOC_REQBUFS,
	VIDIOC_QUERYBUF,
	VIDIOC_STREAMON,
	VIDIOC_STREAMOFF,
	VIDIOC_QBUF,
	VIDIOC_DQBUF,
	VIDIOC_ENUM_FRAMESIZES,
	VIDIOC_G_CTRL,
	VIDIOC_S_CTRL,
	VIDIOC_QUERYCTRL
}